name: mkdocs-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # Dev tools
  - setuptools
  - setuptools_scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel

  # Testing
  - pytest
  - pytest-cov

  # Examples
  - jupyterlab
  - pandas
  - matplotlib
  - plotly
  - bokeh

  - pip:
    # Package deps
    - mkdocs>=1.1.0,<2
    - nbconvert>=6.0.7,<7
    - jupytext>=1.11.0,<2

    # Testing
    - mkdocs-material
    - mkdocs-minify-plugin
    - pygments
    - pymdown-extensions
