name: demo

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: demo-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Deploy demo website

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        node-version: [18]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1

      # ------------------------------------------------------------------------
      # Set up JS

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load cached node_modules
        id: cached-node_modules
        uses: actions/cache@v3
        with:
          path: js/node_modules
          key: >
            node_modules
            ${{ runner.os }}
            node-${{ matrix.node-version }}
            ${{ hashFiles('js/package*.json') }}

      - name: Install JS deps
        if: steps.cached-node_modules.outputs.cache-hit != 'true'
        run: |
          task js-install

      - name: Build JS
        run: |
          task js-build

      # ------------------------------------------------------------------------
      # Setup Python

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # - uses: actions/cache@v3
      #   id: cached-python-env
      #   with:
      #     path: ${{ env.pythonLocation }}
      #     key: >
      #       python
      #       ${{ runner.os }}
      #       python-${{ matrix.python-version }}
      #       ${{ hashFiles('pyproject.toml') }}
      #       ${{ hashFiles('requirements/*') }}

      - name: Install dependencies
        # if: steps.cached-python-env.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements/pyproject.txt

      - name: Install Hatch
        run: |
          pip install --upgrade hatch

      # ------------------------------------------------------------------------
      # Test

      - name: Build package
        run: |
          task build

      - name: Install package
        run: |
          pip install dist/*.tar.gz
          pip freeze

      - name: Build demo docs
        run: |
          task demo-build

      # ------------------------------------------------------------------------
      # Publish

      - name: Upload to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=demo/site --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
